/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clienttcp.ui;

import clienttcp.net.TCPClient;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ian
 */
public class OrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel
     */
    TCPClient tcp;
    DefaultTableModel menuModel;

    public OrderPanel() {
        initComponents();
    }

    public OrderPanel(TCPClient tcp) {
        this();
        this.tcp = tcp;

        menuModel = new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Nama", "Harga", "Qty Pesan"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return col == 3;
            }
        };
        tableMenu.setModel(menuModel);
        loadMenu();
    }

    private void loadMenu() {
        try { // Call Web Service Operation
            clienttcp.wsclient.UASWebService_Service service = new clienttcp.wsclient.UASWebService_Service();
            clienttcp.wsclient.UASWebService port = service.getUASWebServicePort();
            java.util.List<clienttcp.wsclient.MenuItem> menuItems = port.getAllMenu();

            menuModel.setRowCount(0);
            if (menuItems != null) {
                for (clienttcp.wsclient.MenuItem m : menuItems) {
                    menuModel.addRow(new Object[]{m.getId(), m.getName(), m.getPrice(), 0});
                }
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal memuat menu dari Web Service.\n" + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoadMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();
        btnSubmitOrder = new javax.swing.JButton();
        txtReservationId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        btnLoadMenu.setText("Muat Menu");
        btnLoadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadMenuActionPerformed(evt);
            }
        });

        tableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMenu);

        btnSubmitOrder.setText("Submit");
        btnSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitOrderActionPerformed(evt);
            }
        });

        jLabel1.setText("Reservation Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoadMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmitOrder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadMenu)
                    .addComponent(btnSubmitOrder)
                    .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadMenuActionPerformed
        loadMenu();
    }//GEN-LAST:event_btnLoadMenuActionPerformed

    private void btnSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitOrderActionPerformed
        String resIdStr = txtReservationId.getText().trim();
        if (resIdStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Isi Reservation ID terlebih dahulu");
            return;
        }

        StringBuilder items = new StringBuilder();
        for (int i = 0; i < menuModel.getRowCount(); i++) {
            int menuId = (int) menuModel.getValueAt(i, 0);
            int qty = Integer.parseInt(menuModel.getValueAt(i, 3).toString());
            if (qty > 0) {
                if (items.length() > 0) {
                    items.append(",");
                }
                items.append(menuId).append(":").append(qty);
            }
        }

        if (items.length() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih minimal 1 item dengan qty > 0");
            return;
        }

        try {
            String cmd = "CREATE_ORDER|" + resIdStr + "|" + items;
            String resp = tcp.sendCommand(cmd);
            if (resp != null && resp.startsWith("OK")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pesanan berhasil dibuat!\n" + resp);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal: " + resp, "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal terhubung ke Server TCP.\n" + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadMenu;
    private javax.swing.JButton btnSubmitOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMenu;
    private javax.swing.JTextField txtReservationId;
    // End of variables declaration//GEN-END:variables
}
